/*
 * Copyright 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package leap.orm;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import leap.core.AppConfig;
import leap.core.BeanFactory;
import leap.core.annotation.ConfigProperty;
import leap.core.annotation.Configurable;
import leap.core.ioc.PostConfigureBean;
import leap.lang.New;
import leap.lang.exception.ObjectNotFoundException;
import leap.lang.naming.NamingStyles;
import leap.orm.config.OrmConfigExtension;

@Configurable(prefix=OrmConfig.KEY_PREFIX)
public class DefaultOrmConfig implements OrmConfig,PostConfigureBean {

    protected boolean     autoCreateTables           = false;
    protected boolean     autoMappingTables          = false;
	protected boolean     autoGenerateColumns        = false;
	protected boolean     autoGenerateOptimisticLock = false;
	protected boolean     modelCrossContext          = false;
    protected boolean     queryFilterEnabled         = false;
    protected String      queryFilterName            = "query_filter";
    protected String      queryFilterPrefix          = "entity:";
    protected String      queryFilterAlias           = "t";
    protected long        defaultMaxResults          = -1;
    protected String      optimisticLockFieldName    = OrmConstants.LOCK_VERSION;
    protected Set<String> autoGeneratedFieldNames    = New.linkedHashSet(OrmConstants.CREATED_AT,OrmConstants.UPDATED_AT);
	protected String      tableNamingStyle           = NamingStyles.NAME_LOWER_UNDERSCORE;
	protected String      columnNamingStyle          = NamingStyles.NAME_LOWER_UNDERSCORE;
    protected String      defaultSerializer          = "json";

    protected SerializeConfig              defaultSerializeConfig;
    protected Map<String, SerializeConfig> serializeConfigs = new HashMap<>();
    protected Map<String, SerializeConfig> serializeConfigsImv = Collections.unmodifiableMap(serializeConfigs);

    @Override
    public boolean isAutoCreateTables() {
        return autoCreateTables;
    }

    @ConfigProperty
    public void setAutoCreateTables(boolean autoCreateTables) {
        this.autoCreateTables = autoCreateTables;
    }

    @Override
    public boolean isAutoMappingTables() {
        return autoMappingTables;
    }

    @ConfigProperty
    public void setAutoMappingTables(boolean autoMappingTables) {
        this.autoMappingTables = autoMappingTables;
    }

    @Override
    public long getDefaultMaxResults() {
	    return defaultMaxResults;
    }
	
	@Override
    public String getOptimisticLockFieldName() {
	    return optimisticLockFieldName;
    }

	public boolean isAutoGenerateColumns() {
	    return autoGenerateColumns;
    }
	
	public boolean isAutoGenerateOptimisticLock() {
		return autoGenerateOptimisticLock;
	}

    @Override
    public boolean isModelCrossContext() {
        return modelCrossContext;
    }

    @Override
    public boolean isQueryFilterEnabled() {
        return queryFilterEnabled;
    }

    @ConfigProperty
    public void setQueryFilterEnabled(boolean queryFilterEnabled) {
        this.queryFilterEnabled = queryFilterEnabled;
    }

    public String getQueryFilterName() {
        return queryFilterName;
    }

    @ConfigProperty
    public void setQueryFilterName(String queryFilterName) {
        this.queryFilterName = queryFilterName;
    }

    @Override
    public String getQueryFilterPrefix() {
        return queryFilterPrefix;
    }

    @ConfigProperty
    public void setQueryFilterPrefix(String queryFilterPrefix) {
        this.queryFilterPrefix = queryFilterPrefix;
    }

    public String getQueryFilterAlias() {
        return queryFilterAlias;
    }

    @ConfigProperty
    public void setQueryFilterAlias(String queryFilterAlias) {
        this.queryFilterAlias = queryFilterAlias;
    }

    @ConfigProperty
	public void setAutoGenerateOptimisticLock(boolean autoGenerateOptimisticLockField) {
		this.autoGenerateOptimisticLock = autoGenerateOptimisticLockField;
	}

	public Set<String> getAutoGeneratedFieldNames() {
	    return autoGeneratedFieldNames;
    }
	
	@ConfigProperty
	public void setOptimisticLockFieldName(String optimisticLockFieldName) {
		this.optimisticLockFieldName = optimisticLockFieldName;
	}

	@ConfigProperty
	public void setDefaultMaxResults(long maxResults) {
		this.defaultMaxResults = maxResults;
	}

	@ConfigProperty
	public void setAutoGenerateColumns(boolean autoGenerateFieldsForModel) {
		this.autoGenerateColumns = autoGenerateFieldsForModel;
	}

	@ConfigProperty
	public void setAutoGeneratedFieldNames(Set<String> autoGeneratedFieldsForModel) {
		this.autoGeneratedFieldNames = autoGeneratedFieldsForModel;
	}

    @ConfigProperty
    public void setModelCrossContext(boolean modelCrossContext) {
        this.modelCrossContext = modelCrossContext;
    }

    @Override
    public String getTableNamingStyle() {
	    return tableNamingStyle;
    }
	
	@ConfigProperty
	public void setTableNamingStyle(String tableNamingStyle) {
		this.tableNamingStyle = tableNamingStyle;
	}

	@Override
    public String getColumnNamingStyle() {
	    return columnNamingStyle;
    }
	
	@ConfigProperty
	public void setColumnNamingStyle(String columnNamingStyle) {
		this.columnNamingStyle = columnNamingStyle;
	}

    @Override
    public String getDefaultSerializer() {
        return defaultSerializer;
    }

    @ConfigProperty
    public void setDefaultSerializer(String defaultSerializer) {
        this.defaultSerializer = defaultSerializer;
    }

    @Override
    public SerializeConfig getDefaultSerializeConfig() {
        return defaultSerializeConfig;
    }

    @Override
    public SerializeConfig getSerializeConfig(String name) throws ObjectNotFoundException {
        SerializeConfig sc = serializeConfigs.get(name.toLowerCase());
        if(null == sc) {
            throw new ObjectNotFoundException("Serializer config of format'" + name + "' not found");
        }
        return sc;
    }

    @Override
    public Map<String, SerializeConfig> getSerializeConfigs() {
        return serializeConfigsImv;
    }

    @Override
    public void postConfigure(BeanFactory factory, AppConfig config) throws Throwable {
        OrmConfigExtension extension = config.getExtension(OrmConfigExtension.class);

        extension.getSerializeConfigs().forEach((format, c) -> {
            serializeConfigs.put(format, c);
        });

        defaultSerializeConfig = serializeConfigs.get(defaultSerializer.toLowerCase());
    }
}